default: &default # Define uma âncora chamada "default" para reutilização posterior
  adapter: postgresql # Configura o adaptador de banco de dados como PostgreSQL
  encoding: unicode # Define a codificação do banco de dados como Unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %> # Define o tamanho do pool de conexões de banco de dados com base em uma variável de ambiente chamada "RAILS_MAX_THREADS" (padrão: 5)

development: # Configurações para o ambiente de desenvolvimento
  <<: *default # Herda as configurações definidas em "default"
  database: web_healthy_care_development # Define o nome do banco de dados para o ambiente de desenvolvimento

test: # Configurações para o ambiente de teste
  <<: *default # Herda as configurações definidas em "default"
  database: web_healthy_care_test # Define o nome do banco de dados para o ambiente de teste

production: # Configurações para o ambiente de produção
  <<: *default # Herda as configurações definidas em "default"
  database: web_healthy_care_production # Define o nome do banco de dados para o ambiente de produção
  username: web_healthy_care # Define o nome de usuário do banco de dados para o ambiente de produção
  password: <%= ENV["WEB_HEALTHY_CARE_DATABASE_PASSWORD"] %> # Obtém a senha do banco de dados a partir de uma variável de ambiente chamada "WEB_HEALTHY_CARE_DATABASE_PASSWORD"
